### PR TITLE
Always use a port to connect the test Dummy Client

### LINKED ISSUE #30: dummy_channel() using sockets fails when OpenTelemetry instrumentation is active
### What versions of the following are you using?

* `python`: 3.10
* `grpc-interceptor`: 0.13.2
* `grpcio`: 1.51.0
* `protobuf`: 3.20.3

### What operating system (Linux, Windows,...) and version?

Mac, Linux

### What did you do?

Using the `dummy_client()` while global OpenTelemetry instrumentation was active.

### What did you expect to see?

Tests succeed.

### What did you see instead?

Tests failed.

### Anything else we should know about your project / environment?

Adding global OpenTelemetry instrumentation as documented [here](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/grpc/grpc.html):
```python
from opentelemetry.instrumentation.grpc import GrpcInstrumentorClient, GrpcInstrumentorServer

GrpcInstrumentorServer().instrument()  # type: ignore[no-untyped-call]
GrpcInstrumentorClient().instrument()  # type: ignore[no-untyped-call]
```
causes this error:
```
  File "/.../tests/test_interceptors.py", line 34, in test_returns_method_result
    assert client.Execute(DummyRequest(input="foo")).output == "foo"
  File "/.../.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/grpcext/_interceptor.py", line 69, in __call__
    return self._interceptor.intercept_unary(
  File "/.../.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_client.py", line 154, in intercept_unary
    return self._intercept(request, metadata, client_info, invoker)
  File "/.../.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_client.py", line 145, in _intercept
    raise exc
  File "/.../.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/_client.py", line 131, in _intercept
    result = invoker(request, metadata)
  File "/.../.venv/lib/python3.10/site-packages/opentelemetry/instrumentation/grpc/grpcext/_interceptor.py", line 59, in invoker
    return self._base_callable(
  File "/.../.venv/lib/python3.10/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/.../.venv/lib/python3.10/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception calling application: not enough values to unpack (expected 2, got 1)"
	debug_error_string = "UNKNOWN:Error received from peer unix:/var/folders/2r/yyz1661s4j91vhdkzktg66z80000gn/T/a8ac6951-2094-4bed-8dfc-678465677448.sock {created_time:"2023-03-26T13:05:06.353245+10:00", grpc_status:2, grpc_message:"Exception calling application: not enough values to unpack (expected 2, got 1)"}"
>
```
I suspect that’s because the `dummy_client` on non Windows hosts opens a UNIX socket rather than a port:

https://github.com/d5h-foss/grpc-interceptor/blob/1c2ec428cb7c7796f68e23cb254129b068aeb839/src/grpc_interceptor/testing/dummy_client.py#L227-L232

The related OpenTelemetry code ([src](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/e4d8f10ecd7bcd29c119af0e3ea7c30d4a383f4b/instrumentation/opentelemetry-instrumentation-grpc/src/opentelemetry/instrumentation/grpc/_server.py#L254-L256)) stumbles because
```python
context.peer()
```
returns `unix:` and therefore
```
context.peer().split(",")[0].split(":", 1)[1].rsplit(":", 1)
```
returns `['']` which can’t unpack to `ip` and `port`. If I change to using ports on Mac/Linux, the tests work.

It looks to me like OpenTelemetry doesn’t support channels over sockets, which is probably a feature request for them. However, until then is there any chance you’d welcome a PR that adds a `use_sockets` kwarg to `dummy_channel()` to explicitly enable UNIX sockets and otherwise fall back to ports?

### PR DESCRIPTION
**Pull request by jenstroeger**
Fixes #30

### CODE REVIEW

**Comment by jenstroeger** [comment]
@d5h any chance you can merge and release an update soon — provided you’re ok with the changes.

I wasn’t sure about your `import` conventions, and searching for a random available port is funky, but maybe that’s ok for a Dummy test client 🤓

**Review by d5h — CHANGES_REQUESTED** [review]
Good news and bad news.

Bad news first. This code has a race condition that might be likely to occur if someone is parallelizing their tests. The race condition is that time of check is done by `connect_ex`, but time of use is the `add_insecure_port` call. Hence, two parallel tests could both confirm that port `50051` is free, and then both try to use it.

It gets worse too (but good news coming, I promise). I did a little testing and just realized there's a fundamental issue with this whole approach. `grpc` by default sets `SO_REUSEPORT`, so it will happily allow you to create two distinct services listening on the same port. When a request goes to that port, the kernel will pick one to send the request to. So it's possible that two parallel tests could both try to use port `50051`, and instead of failing immediately, the service in one test could get the request from a different test (or none at all).

`grpc` provides the option `grpc.so_reuseport` to disable this, but when I did some testing (on a Mac), it didn't seem to work (and I'm not sure what the problem is).

Ok, but now for the good news. While playing around with this I realized there's a much simpler and more robust way to do it. If you bind to port `0`, Linux will assign a random unused port to you. You can do this in `grpc` with `server.add_insecure_port("localhost:0")` and that will return the actual port it uses (I knew that binding to port `0` would give you a random port, but didn't know that `grpc` had a way to return the port to you, otherwise I would have suggested this before. Sorry!).

So it's actually fairly easy to do this and avoid race conditions. We just need to reorder the code to create the server before creating the client channel. Then we can use whatever port gets returned by `server.add_insecure_port` for the client channel. Reordering the code should be trivial for the sync server. The `asyncio` service runs in another thread (`_AsyncServerThread`), but you can assign the random port as an attribute on the thread object, and then fetch it after the `wait_for_server` call. So this part should also (hopefully) be fairly easy.

If the new approach works then I can merge fairly quickly after that. Remember to also bump the version number as per the `CONTRIBUTING.md` doc. Thanks for the PR!

**Comment by jenstroeger** [comment]
> This code has a race condition […]

You’re absolutely right, I missed that 🤦🏻‍♂️

> So it's actually fairly easy to do this and avoid race conditions. […]

Thanks for digging into this, always happy to learn something new! I’ll try to get to this today or tomorrow.

**Comment by d5h** [comment]
Hi @jenstroeger,

I have some free time for the next few days so can finish this up for you if you'd like. Let me know. :)

**Comment by jenstroeger** [comment]
> I have some free time for the next few days so can finish this up for you if you'd like. Let me know. :)

That would be great help, I’m tied down Wed and Thu and earliest would be this coming weekend. Please feel free to add to this PR 🤓

**Comment by d5h** [comment]
Ok, this should be fixed now by https://github.com/d5h-foss/grpc-interceptor/pull/35. Since it was a different approach, it was easier to just make a new branch than to rebase this one and revert unneeded changes. I'll close this one. Thanks!

**Pull request closed without merging**
